### ISSUE TITLE
Should we source papers on Sci-hub ?

### ISSUE THREAD

**Issue by ThatIsAPseudo** [CaptainFact/captain-fact#102]
## User story 

As a fact-checker, I wonder if I can use a Sci-hub link to source a paper. Indeed, Sci-hub provide a link to share a publication freely, but I don't know if I have the right to use it.

![sci-hub](https://user-images.githubusercontent.com/17936055/56825675-23e3fc80-685a-11e9-9ba2-c9696b770e7d.png)

## Best solution for this problem

One can consider Sci-hub as a great service promoting free sharing of knowledge, or as a pirate website that shares papers without the consent of their authors.
Moreover, the website has been blocked in some countries by several ISPs, and is kind of illegal.

So, the question is : **Can we use a Sci-hub link as a source or do we have to find another source ?**

**Comment by Betree** [comment]
Hi @ThatIsAPseudo, thanks for asking that. We already discussed this topic internally in the past but never made a public statement to express our position. I'll post the answer here and we should keep the issue open until we find the proper place to display it on the website (maybe we should add an FAQ section in the Help?).

Scientific literature editors such as Elsevier and Springer Nature defend a model that is against all the values of this project: transparency, openness, and freedom of information.

As the legal representative for https://captainfact.io, I am aware of the risks I  am facing by allowing users to post links to Sci-Hub. I can confirm that nothing will be done to block them. If justice forces us to do so we will find technical workarounds to preserve the links.

So not only do we allow posting sources from Sci-Hub/LibGen, but we will also encourage it as much as we can. Let's have an achievement for users that post links to Sci-Hub (https://github.com/CaptainFact/captain-fact/issues/103).

**Comment by MarcBrillault** [comment]
For the moment, I linked to the original, closed paper editor. But it's always one copypaste away from sci hub.

**Comment by ThatIsAPseudo** [comment]
Closing since my question was answered.
