### ISSUE TITLE
Google doesn't list videos anymore

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#104]
Videos are not listed on Google anymore. Others pages are still listed properly so this may be linked to the fact that we use websocket on this page.

For all videos, Google flags them as `Soft 404`.

Also worth mentioning: the following error appears in Google's crawler:

```
Uncaught SyntaxError: Unexpected token =>
https://captainfact.io/vendor.a75cd4c090a262ce0f62.js:20
```

So `browserlist` may be the answer to solve this.

**Comment by Miragide** [comment]
Its ok now @Betree ?

**Comment by Betree** [comment]
Yep, resolved with the migration to Netlify!
