### ISSUE TITLE
Translations system improvements

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#105]
- [x] Change frontend to use JSON instead of JS
- [x] Add the project on https://hosted.weblate.org/hosting/

**Comment by Betree** [comment]
Message sent to weblate

**Comment by BoFFire** [comment]
@Betree Hi ! :)
Update : https://hosted.weblate.org/projects/captainfact-frontend-ui/

**Comment by Betree** [comment]
Amazing @BoFFire! I'm closing this, I'll follow up to merge the translations
