### ISSUE TITLE
Shifted time fact

### ISSUE THREAD

**Issue by Plinz** [CaptainFact/captain-fact#108]
## User story 

Some youtube live are edited after the live to remove the blank start of the video.
So all the facts on the video are shifted by a certain amount of time (some time 15min) compared to the video.
Today the only way is to pass on all facts and made the change manually (which can be long because the button only shifts by one second).

## Best solution for this problem

I see some solutions :
- Add a global shift button (but problem of permission ?)
- Change the way to shift the time so that you can directly enter a time without using the buttons
- Be able to give the current time of the video when modifying a fact

**Comment by Betree** [comment]
Hello @Plinz, we have a feature to globally shift the statements on a video - however there's a minimum reputation required to have access to it. YouTube shifting videos is a real pain, we would love to have something for it.

I'll close this for now but feel free to add more ideas if you see ways to improve this.

![image](https://user-images.githubusercontent.com/1556356/60213191-3f23b600-9863-11e9-8a93-013aa4ad2c09.png)
