### ISSUE TITLE
Ajouter un lien de contact dans le menu

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#111]
Aujourd'hui, trouver le lien de contact n'est pas évident (dans la partie aide).

Je propose d'ajouter un raccourci vers cette page **https://captainfact.io/help/contact**
dans le menu.

**Comment by steelstyle** [comment]
How should this look like ?

**Comment by Miragide** [comment]
> How should this look like ?

@steelstyle I suggest:
@styled-icons/bootstrap/EnvelopeFill
from https://styled-icons.js.org/?s=enve

Like others menu li:
![image](https://user-images.githubusercontent.com/15331478/95026654-2d9aa200-0693-11eb-95a4-483e54c78c21.png)

**Comment by steelstyle** [comment]
@Betree Any concerns regarding the approach ?
