### ISSUE TITLE
Notification not clickable on mobile

### ISSUE THREAD

**Issue by fbouffetier** [CaptainFact/captain-fact#112]
## Make notification linked to Video/Comment
Get the notification on platform cliakable and linked to the reply/comment/update

## Best solution for this problem

No idea, but I'm not quiet you will find a easy solution

**Comment by Betree** [comment]
@fbouffetier c'est déjà le cas non ?

![Peek 15-10-2019 20-48](https://user-images.githubusercontent.com/1556356/66860315-3c251080-ef8d-11e9-88d0-e45bb45c640f.gif)

**Comment by Betree** [comment]
Update: link doesn't work properly on mobile
