### ISSUE TITLE
Add an introduction to video's pages

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#114]
Afin d'améliorer la compréhension de la page pour les visiteurs, ajouter le message en haut à droite :
![intro](https://user-images.githubusercontent.com/15331478/67700973-55778500-f9af-11e9-9680-80be6915bab7.png)

FR proposition

> Vérification collaborative de la vidéo
> Ci-dessous, les membres de CaptainFact peuvent citer les passages de la vidéo à vérifier. Les citations sont confirmées ou réfutées avec des sources. Les vérifications s'affichent ensuite directement dans la vidéo, à l'écran de tous les utilisateurs de l'extension CaptainFact ([lien de téléchargement](https://captainfact.io/extension)).

--------------

EN proposition

> Collaborative fact-checking of the video
> Here, CaptainFact's members can quote video's moments that should be verified. Quotes have to be confirm or refute with sources. All verifications are displayed directly on video, on screen of all CaptainFact extension's users ([link to download it](https://captainfact.io/extension)).

**Comment by Miragide** [comment]
## Message improvement 

![cf-update-video-introduction](https://user-images.githubusercontent.com/15331478/67967676-4fc7ac80-fc06-11e9-850e-9fc69e3317db.jpg)
FR

- **Citez un passage de vidéo** à l'aide du bouton (+).
- **Ajoutez une source** ou un commentaire en dessous des citations.
- **Évaluez la pertinence des sources** et commentaires avec les flèches ^ et v.
- **Recevez de la réputation à chaque évaluation positive** et [débloquez de nouveaux droits sur le site](https://captainfact.io/help/privileges).

EN
- Quote a video's statement with (+) button.
- Add sources or comments behind the statements.
- Rate sources quality with up votes or down votes.
- Get reputation for each up votes on your job and [unlock new privileges on CaptainFact](https://captainfact.io/help/privileges).

**Comment by fbouffetier** [comment]
Remplacer : "Ajoutez une source ou un commentaire en dessous des citations." 
Par : "Confirmez, refutez ou commentez les citations par des sources."

**Comment by fbouffetier** [comment]
On parle de citation au point 2, ne devrait-on pas parler de citation dans le premier point plutôt que de 'passage'?
ref:"Citez un passage de vidéo"

**Comment by Miragide** [comment]
« Ajoutez une source ou un commentaire » est le nom exact du bouton pour réaliser cette action. Changer la formulation me parait prêter à confusion.
« Citez un passage de vidéo à l'aide du bouton (+). »
Ici, c'est un passage avant d'être cité et de devenir citation, je crois ?

**Comment by Miragide** [comment]
Done
