### ISSUE TITLE
New page: last statements list

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#115]
## Pourquoi créer une liste globale des dernières citations à vérifier ?
- La plupart du temps, les citations peuvent être comprises et vérifiées, même sortie du cadre de la page de vidéo sur laquelle elles sont aujourd'hui listées.
- Les fact-checkeur peuvent préférer vérifier des informations individuellement d'une vidéo et aujourd'hui, ils n'ont aucun moyen de le faire, autre que d'aller visiter laborieusement les vidéos une par une.
- La visibilité des nouvelles activités s'en retrouvera facilitée alors qu'aujourd'hui, on ne peut pas voir quelles sont les dernières contributions (pour surveiller ou prêter main forte).
- Pour faire venir régulièrement des visiteurs, il faut du nouveau contenu intéressant et régulier, facile d'accès, semblable à un fil d'actualité sur un réseau social.

L'ajout d'une telle page peut rendre le site plus intéressant, sur bien des aspects.

![fil-de-citations](https://user-images.githubusercontent.com/15331478/67712553-7eeedb80-f9c4-11e9-8452-0cbef9d78576.jpg)

**Comment by MarcBrillault** [comment]
+1, et ravi d'avoir été screenshoté ici 😄

**Comment by Miragide** [comment]
Je fusionne avec cette issue : https://github.com/CaptainFact/captain-fact/issues/10
