### ISSUE TITLE
Follow CaptainFact on Mastodon ?

### ISSUE THREAD

**Issue by Didou09** [CaptainFact/captain-fact#120]
## User story 

As a user, I was wondering whether it would be possible to follow CaptainFact on [Mastodon ](https://joinmastodon.org/) instead of / in addition to Twitter ? 

## Best solution for this problem

I see two options:
* CaptainFact could post directly on mastodon
* The twitter account of CaptainFact could be automatically replicated to Mastodon via a bot, usign for example this tutorial:
https://dev.to/ayushsharma/tweet-toot-building-a-bot-for-mastodon-using-python-5a6d

**Comment by Miragide** [comment]
@Didou09 Thank, this is a good idea. CaptainFact should join https://mamot.fr 
Maybe you want to work on it?
It would be great!

**Comment by Didou09** [comment]
Nice, I have an account on this one already.
I can try to take care of it, I have an account on mamot.fr and I know python.
I'm already making a bot to replicate Euroscipy's twitter account on Mastodon.

But, if I do it it won't be before January 2020, because I need to buy a raspberry to host Euroscipy's and CaptainFact's bots.
Also, I'll try to leave it on and connected as often as possible, but I can't guarantee it will be operational 100 % of the time (there may be occasional cut due to blackouts or connection issues).
Deal ? (for a first version at least ?)

**Comment by Miragide** [comment]
@Didou09 
> if I do it it won't be before January 2020

Are you still ok to work on it?

If you are french, you should join us on our forum to make the deal:
https://forum.captainfact.io

**Comment by Didou09** [comment]
Yes, I got the raspberry,
now I need to find the time to actually do it, 
it should be possible in the coming days / weeks
I am french, I'll have a look at the forum, thanks

**Comment by Miragide** [comment]
Thank! I'm waiting for you here: https://forum.captainfact.io/t/issue-captainfact-sur-mastodon/180

**Comment by Didou09** [comment]
So I tried to publish on the forum you indicated but new users can only publish 2 lines per message, which is not sufficient, so I publish my message here instead :

**Comment by Didou09** [comment]
(Desole pour les accents, clavier qwerty)

Alors bonjour,

Pour publier sur mastodon, il faut deja creer un compte mastodon pour CaptainFact, et donc choisir une instance. J'ai cru comprendre, et ca me parait une bonne idee, que ce serait l'instance de la Quadrature du Net (mamot.fr, sur la laquelle je suis a titre perso) qui serait preferee, vous confirmez ?
Ensuite il me semble qu'il y a 2 possibilites:
* soit un humain publie des messages directement sur Mastodon pour CaptainFact (celui qui gere la com je suppose ?
* Soit on met en place un petit robot qui replique les messages twitters de CaptainFact sur son compte Mastodon

Si c'est la premiere option qui est retenue a priori j'apportereai pas grand chose, 
Si vous preferez la seconde je peux filer un coup de main.

En efet, je viens de faire un test d'un script python qui interroge un compte twitter, repere les derniers twits, et les replique sur un compte mastodon.
Je l'ai fait avec le compte de la conference Euroscipy (avec l'accord des organisateurs), ca a l'air de fonctionner : 
* J'ai suivi le tuto en ligne [ici](https://dev.to/ayushsharma/tweet-toot-building-a-bot-for-mastodon-using-python-5a6d)
* J'ai cree un compte Euroscipy sur une [instance](https://botsin.space/about) qui ne sert qu'a heberger des robots replicateurs
* J'ai clone le repo github mis a dispositio sur un raspberry tout neuf
* J'ai fait tourne, ca a l'air de marcher : https://botsin.space/web/accounts/180022 

J'ai pas pu le tester beaucoup parce que le compte twitter d'Euroscipy n'a publie qu'un seul message depuis...

Est-ce que ces modalites vous conviendraient ?
Le cas echeant je peux m'en occuper, mais:
* je ne peux pas, pour l'instant, laisser mon raspberry connecte 24/24 7/7, donc la replication de twitter vers mastodon sera forcement un peu irreguliere et intermittente.
* Ca peux suffire pour des tests et pour le debut, ensuite, si ya un nombre significatifs de gens qui suivent CaptainFact sur Mastodon, on pourra discuter de comment aller plus loin (ex: acheter un petit truc minimaliste genre arduino Uno qui servirait qu'a ca et qui serait connecte 24/24, avec une conso;;ation electrique minimale)

QU'en pensez vous ?
Didier

**Comment by Miragide** [comment]
Bonjour @Didou09 
> but new users can only publish 2 lines per message,

J'ai résolu le problème, les nouveaux utilisateurs ne pouvaient effectivement pas publier plus de deux liens dans un message, ce que je trouve un peu trop contraignant, alors merci pour la remarque qui aidera les prochains arrivants sur le forum.

Un compte CaptainFact a été fait sur mamot : https://mamot.fr/web/accounts/305043

> soit un humain publie des messages directement sur Mastodon pour CaptainFact

Notre petite équipe a du mal à débloquer du temps pour ce genre de chose, donc la seconde option proposée serait vraiment idéale, peu importe si le bot n'est pas parfaitement réactif. Des publications en retard valent mieux que pas de publications du tout :) 

Merci encore pour cette initiative.

**Comment by Didou09** [comment]
De rien, 

Alors j'ai commence, 
deja merci pour la creation du compte, mais:
si ce compte doit etre le miroir du compte twitter, il faut specifier dans ses parametres que cest un robot (bot), et lui donner les acces et lecture et ecriture uniquement, est-ce le cas ?
D'autre part j'aurai besoin d'acceder a sa configuration pour lui faire generer un code d'authentification (token) que le script python utilisera pour s'authentifier.

Enfin, et pour info, j'ai ouvert un ticket (issue) sur le github du mec qui a fait le tuto pour lui demander la meilleure maniere de proceder pour que le meme robot python actualise les comptes de plusieurs associations / organisations en meme temps ([ici](https://github.com/ayush-sharma/tweet-toot/issues/15), pour info).

**Comment by Miragide** [comment]
D'accord, je t'ai envoyé un message privé sur le forum avec les informations.

**Comment by Didou09** [comment]
Ok merci,

J'ai commence a faire les (legeres) modifs necessaires dans le compte, j'attends encore un coup de main du createur du script et ca sera fini

**Comment by Didou09** [comment]
Salut !
Alors j'ai fait un test avec l'aide du developpeur: [ca marche](https://mamot.fr/web/accounts/305043).

Mais il reste un soucis : j'ai l'impression que les toots n'ont pas ete postes dans le ordre chronologique que les twits associes.
On y travaille, je vous tiens au courant

**Comment by Miragide** [comment]
https://crossposter.masto.donte.com.br
