### ISSUE TITLE
"File an issue on GitHub" button open opencollective github instead of captainfact github

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#126]
## "File an issue on GitHub" button open opencollective github
https://github.com/opencollective/opencollective/issues/new
instead of captainfact github?
https://github.com/CaptainFact/captain-fact/issues/new/choose

I suggest to change contact support url for captainfact forum url:
https://forum.captainfact.io/c/aide

![image](https://user-images.githubusercontent.com/15331478/74987463-82a6e200-543b-11ea-8a97-e2a35a06b32e.png)

**Comment by Betree** [comment]
Uuh that's ugly
