### ISSUE TITLE
Modify video category (User or partners)

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#128]
We should give the moderator or ambassador ability to switch the video category (user category or partners category),
because it is a frequent need.

I suggest a scrolling menu here:

![image](https://user-images.githubusercontent.com/15331478/75185377-44b10300-5746-11ea-98f7-99778a561832.png)

EN : "Change video category (moderator)" with the two choices

FR : Changer la catégorie de la vidéo (modération)

**Comment by Betree** [comment]
This is not something that you need to do very often (not more than once per video). So I wouldn't overload the main interface with it, it can be added to the `Edit video` modal which purpose is precisely to edit the metadata related to the video:

![image](https://user-images.githubusercontent.com/1556356/75378562-32fd6600-58d4-11ea-9ee2-9e1af1639ce3.png)

![image](https://user-images.githubusercontent.com/1556356/75378583-3db7fb00-58d4-11ea-8b79-4fa800bb91d1.png)

**Comment by Miragide** [comment]
done
