### ISSUE TITLE
List of videos: thumbnails are deformed

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#133]
It looks like this bug appears since the update of facebook lives:
https://captainfact.io/videos
![image](https://user-images.githubusercontent.com/15331478/77213724-256e8100-6b0c-11ea-83d9-fac229d45e8d.png)

**Comment by Betree** [comment]
Thanks for the report, good guess - I broke that in the Facebook PR indeed!

**Comment by Betree** [comment]
Fix deployed, entries updated
