### ISSUE TITLE
Remove "fact-checker" and "viewer" presence informations on video page

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#137]
![54688641-4e85bb80-4b1e-11e9-9c9f-b52c05a7be58](https://user-images.githubusercontent.com/15331478/78513718-e566f980-77ad-11ea-998d-7e0a7442f758.png)

## User story 
Les indicateurs de présences sont souvent à 0 et créent de la confusion.
Durant une session de test, j’ai entendu un utilisateur dire : 
_« ha, mais il n’y a que 2 fact-checkers sur cette vidéo ? »_
ne comprenant pas la signification.

Basile, ambassadeur :

> 100% pour supprimer, j’ai jamais compris ces indicateurs et la différence entre les 2 métriques.
> Le niveau d’activité sur une vidéo est visible par le nombre de publications

## How we can improve that

Supprimer les indicateurs.

Note de Betree
> **We can delete it from frontend but let's keep the backend feature, it can be interesting for us in the future to know how many people are connected at the same time**

________

Merci @Vayel pour cette issue qui a révélé le problème : 
https://github.com/CaptainFact/captain-fact/issues/77

**Comment by Betree** [comment]
We can delete it from frontend but let's keep the backend feature, it can be interesting for us in the future to know how many people are connected at the same time
