### ISSUE TITLE
Reject Flags has no effect

### ISSUE THREAD

**Issue by fbouffetier** [CaptainFact/captain-fact#139]
**When Flags is rejected, there is no effect on plateform**

*From moderation tools, when a flags is rejected by an admin, flags stays on plateform*

**To Reproduce**

*Steps to reproduce the behavior*

1. Go to 'https://captainfact.io/videos/gLjY?statement=4221'
2. Click on 'Flags'
3. Select Flags type and confirm
4. In moderation tools, rejected the flag.
5. Go back to 'https://captainfact.io/videos/gLjY?statement=4221'

**![image](https://user-images.githubusercontent.com/45431921/81416931-b942ed80-914a-11ea-9e6d-02ded3fc5c55.png)**

**System:**

 - OS: Windows 10
 - Browser: Firefox

**Comment by Betree** [comment]
There must be a consensus before any action is taken (3 if I remember correctly). It's not a one-person decision.

**Comment by Betree** [comment]
See https://captainfact.io/help/moderation for more info

**Comment by fbouffetier** [comment]
My bad, THANKS Benjamin. Will discuss since I think we must update the rule. You can close this non issue.
