### ISSUE TITLE
Passez la langue du site en FR 

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#140]
Aujourd'hui, le site s'affiche en anglais par défaut alors que les utilisateurs sont à + 80 % Français.
Je propose soit que la langue soit automatiquement détectée pour la passer en FR ; soit que la langue soit le français par défaut au lieu de l'anglais.

**Comment by Betree** [comment]
La langue est normalement détectée en fonction du navigateur (si le navigateur est en FR, le défaut est normalement FR). Pour voir si c'est un bug, tu pourrais taper ça dans une console de ton navigateur?

```es6
window.navigator.userLanguage || window.navigator.language
```

**Comment by Miragide** [comment]
> La langue est normalement détectée en fonction du navigateur (si le navigateur est en FR, le défaut est normalement FR). Pour voir si c'est un bug, tu pourrais taper ça dans une console de ton navigateur?
> 
> ```js
> window.navigator.userLanguage || window.navigator.language
> ```
@Betree voici le résultat
Il semble que ça bug effectivement.
![image](https://user-images.githubusercontent.com/15331478/91617996-93f01e80-e989-11ea-92bf-85fdc59746c6.png)

**Comment by Betree** [comment]
Fixed by https://github.com/CaptainFact/captain-fact-frontend/pull/674
