### ISSUE TITLE
Menu: Change text "Videos" for "Video fact-checking"

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#142]
Here:
![image](https://user-images.githubusercontent.com/15331478/94455414-51517a00-01b3-11eb-95e7-71b3be9aefd3.png)

Text EN menu:
Change "Videos" for "Video fact-checking"

Text FR menu:
Change "Vidéos" for "Vérification de vidéos"

Same modifications for page title:
https://captainfact.io/videos

Text EN / FR menu:
Change "contenu" / "content" for "Fact-checking"

Because it's more understandable.

**Comment by ericPennequin** [comment]
Bonjour,
Suite à notre réunion de mardi dernier, Je m'occuperais bien de cette issue pour commencer chez captainFact (pseudo discord eric140). Merci
