### ISSUE TITLE
DisMoi : Nouvelle extension à afficher sur la page "extension"

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#143]
CaptainFact collabore avec le projet DisMoi.io : https://www.dismoi.io afin (à terme) de permettre la vérification de toutes les pages du web et plus seulement les vidéos youtube.

CaptainFact souhaite mettre à jour la page https://captainfact.io/extension : 

![image](https://user-images.githubusercontent.com/15331478/94463975-11dc5b00-01be-11eb-9cb6-8a8ae38deef9.png)

Texte FR : 
> NOUVEAU (FR)
**L’extension DisMoi**
**Pour vérifier toutes les pages du web**
DisMoi permet à CaptainFact d'afficher ses fact-checking directement sur les pages web que vous visitez. DisMoi vous affichera des alertes, afin de vous signaler les arnaques, les fake-news ou des contextualisations en rapport.
PS : Gratuit, sans publicité, open source et respecte votre vie privée
[Suivre CaptainFact sur DisMoi](https://www.dismoi.io/informateurs/55/CaptainFact.io)
[Découvrir cette extension](https://www.dismoi.io)

Texte EN : 

> NEW (FR)
DisMoi web extension
To check the pages you visit
DisMoi allows CaptainFact to post fact-checking notifications directly on any page you browse.
When you visit a web page CaptainFact verified, you are notified by (the DisMoi web extension) | (DisMoi).
Ad-free, no collection of personal data, open source and free.
[Follow CaptainFact on ](https://www.dismoi.io/informateurs/55/CaptainFact.io)
[Learn more about DisMoi](https://www.dismoi.io)

**Comment by MaartenLMEM** [comment]
@Miragide 
NEW
**DisMoi web extension
To check the pages you visit**
DisMoi allows CaptainFact to post fact-checking notifications directly on any page you browse.
When you visit a web page CaptainFact verified, you are notified by (the DisMoi web extension) | (DisMoi).
Ad-free, no collection of personal data, open source and free.
[Follow CaptainFact on DisMoi](https://www.dismoi.io/informateurs/55/CaptainFact.io)
[Learn more about DisMoi](https://www.dismoi.io/)

**Comment by dimitri-bourreau** [comment]
Bonjour,

Je suis ravi d'aider, mais c'est ma première fois sur ce code riche et complexe.

<img width="1173" alt="Capture d’écran 2020-10-15 à 02 26 32" src="https://user-images.githubusercontent.com/32717624/96059382-1e370800-0e8e-11eb-9efc-1a2506ae81f7.png">

Quelqu'un avec une expérience sur l'architecture du projet peut me conseiller sur les _components_ et _className_ à regarder ? 🙏

Il me faudrait aussi la capture / l'image à placer à la droite du texte d'introduction. 👍

[Mon fork](https://github.com/tobudim/captain-fact-frontend/commits/staging)

**Comment by MaartenLMEM** [comment]
Bonjour Dimitri,
Je peux déjà te fournir l'image. voici : https://drive.google.com/file/d/1Dwx3Pz8r7cZO_af6wPpWQhuUEy29Bo4g/view?usp=sharing 
Merci !

**Comment by dimitri-bourreau** [comment]
Bonjour à tous. 😊

Juste un petit rappel :

> Quelqu'un avec une expérience sur l'architecture du projet peut me conseiller sur les components et className à regarder ? 🙏

Si personne n'est disponible, j'essaie dans la semaine de trouver par moi-même et je vous tiens informé de l'avancement. 🙂

**Comment by MaartenLMEM** [comment]
Hello @tobudim je ne peux pas t'aider sur ce point précis, par contre je serai à ta dispo si tu as un besoin (comme l'image dans un autre format) ou une question qui apparait au fil de l'intégration.

**Comment by Betree** [comment]
Salut @tobudim, la page est sur `app/components/Pages/BrowserExtensionsPage.jsx`. N'hésite pas à me mentionner sur cette issue si tu as des questions.

**Comment by Miragide** [comment]
Bonjour @tobudim souhaites tu toujours t'occuper de cette mise à jour ?

**Comment by dimitri-bourreau** [comment]
Oui seulement j'ai beaucoup moins de temps, et la codebase n'est pas simple à appréhender (je savais bien quelle page modifier comme mon fork et ma capture d'écran l'indiquaient).

Si quelqu'un a du temps qu'il n'hésite pas à simplement reprendre mon fork.
Comme je l'ai demandé, il suffit de savoir quels composants et quelles classes utiliser pour avoir l'UI souhaitée. Le reste est déjà modifé.
