### ISSUE TITLE
FR : ajouter une vidéo de présentation de CaptainFact sur la page d'accueil

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#144]
Ajouter cette vidéo youtube 
https://www.youtube.com/watch?v=Hox_CHmC-so
ici (en dessous de la 1ere partie du site) en français uniquement : 
![image](https://user-images.githubusercontent.com/15331478/94472367-ef047380-01ca-11eb-941c-aa217b17eff7.png)

**Comment by francoispeyret** [comment]
PR prêt à être validé 😌

**Comment by Miragide** [comment]
@francoispeyret thank you very much :)
