### ISSUE TITLE
GDPR mention on signup form "I agree that I have read and accepted the CaptainFact Privacy Policy"

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#145]
Here:
https://captainfact.io/signup
![image](https://user-images.githubusercontent.com/15331478/95036257-a3b8fc00-06c7-11eb-997a-ed5b098a84f5.png)

Add a required checkbox:

EN
> By clicking "Sign up", I agree that I have read and accepted the [CaptainFact Privacy Policy](https://captainfact.io/help/privacy).

FR
> En cliquant sur « S'enregistrer » j'accepte [la politique de confidentialité de CaptainFact](https://captainfact.io/help/privacy).

**Comment by francoispeyret** [comment]
i take it

**Comment by wdestin** [comment]
Is this issue still relevant?

**Comment by Betree** [comment]
This was done in https://github.com/CaptainFact/captain-fact-frontend/pull/685, good catch @wdestin
