### ISSUE TITLE
videos do not load / les vidéos ne chargent pas

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#151]
**Describe the bug**
Bug repport from discord user grenouille_maritime#2896
On all video's pages, all browser:
- videos do not load (black screen)
- console error:
![image](https://user-images.githubusercontent.com/15331478/97864778-75036500-1d09-11eb-8d8a-afbeb1b55421.png)

**System**
BitDefender
All browser
Windows 10

**To Reproduce**
I don't know.

**Comment by Daniel-grenouille** [comment]
Error message is related to Google API.
The local network is seen as a botnet by the Google API. The reason remains unknown.
FAI should investigate it within few days.

**Comment by Daniel-grenouille** [comment]
Avant que cela n'arrive, j'ai pas mal utilisé les flèches autour des time-codes pour réajuster le temps des citations dans plusieurs vidéos. Ces multiples clics dont certains très rapprochés, pourraient être la raison : trop d'appels rapprochés des APIs a fait croire à un robot attaquant cette interface.

**Comment by Daniel-grenouille** [comment]
la situation est rétabli après 20h30?... La compréhension du problème n'est pas certaine. 
Je vais utiliser d'utiliser trop souvent les flèches de positionnement du time-code.

**Comment by Betree** [comment]
Pas grand chose qu'on puisse faire du côté de CF si c'est YouTube qui bloque

**Comment by francoispeyret** [comment]
On pourrait éventuellement faire un message d'alerte pour ce cas dans la page ?

**Comment by Daniel-grenouille** [comment]
ajouter un timer si on utilise les flèches plus de 10 fois en 30 secondes ?
ou autre threshold ...
bon juste une idée, Je ne sais aps si c'est faisable/facile.

Le lun. 2 nov. 2020 à 22:24, Benjamin Piouffle <notifications@github.com> a
écrit :
