### ISSUE TITLE
Lower reputation to add unlisted video / baisser la réputation requise pour ajouter des vidéos non listées

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#152]
Bonjour
@steelstyle @Betree 
Je crois qu'il y a eu un soucis de compréhension pour cette issue : https://github.com/CaptainFact/captain-fact/issues/42
Il s'agissait de baisser la réputation requise de 75 à 15 pts, mais seulement pour les vidéos non listées, qui sont traitées différemment des vidéos normales.
Ce qui a été mis en ligne, c'est baisser la réputation requise pour l'ajout de toutes les vidéos.

Pour en savoir plus sur la différence :
>   Les vidéos publiques sont listées sur la page des vidéos et apparaissent dans l'extension pour navigateur.
>   Les vidéos non listées n’apparaîtront ni dans la liste des vidéos ni dans l'extension. Elles vous permettent de travailler sur un contenu sans que celui-ci ne soit mis en avant par la plateforme.
https://captainfact.io/videos/add

Ce n'est pas grave bien-sûr, pas d’inquiétude... nous avons ainsi pu expérimenter cette modification, donc ce n'est pas perdu. Néanmoins maintenant sont ajoutées de nombreuses vidéos qui manquent de pertinence (d'après la communauté) et ce qui est un peu gênant.

Normalement @Betree va donc reverse cette mise à jour pour que l'ajout de vidéo revienne à 75 pts.

Le sujet de baisser la réputation requise pour ajouter des vidéos non listées est toujours d'actualité.
L'enjeu est d'améliorer l’implication en permettant aux nouveaux arrivants de vérifier les vidéos qu'ils veulent - expérimenter librement - sans que cela puisse avoir d'impacts négatifs sur la plateforme CaptainFact.

Merci aux contributeurs :)

**Comment by steelstyle** [comment]
Then it might make sense to reopen the previous bug rather than opening a new one ?
I had a different understanding of between public and unlisted.

I guess one question arises, can user change of the video from unlisted to public and vice versa ?

**Comment by Miragide** [comment]
> Then it might make sense to reopen the previous bug rather than opening a new one ?

I don't know, as you want.

> can user change of the video from unlisted to public and vice versa ?

It will be necessary, but It's not planned yet.
For now, only administrator can switch this, after a request.

I hope my answers suit you :)

**Comment by steelstyle** [comment]
Thanks for the answer.
If you could provide information of how the UI looks (and the text) for the add video page I can probably provide a fix forward.

An example is whether you want to show the toggle button when a user only have 15pts only.
In the case it is shown, what is the look of disabled button on CaptainFact ?

**Comment by steelstyle** [comment]
@Miragide also let me know if you feel that this decision is up to me.

**Comment by Miragide** [comment]
@steelstyle good question.
If user have 15 pts or less, I propose to block switch / toggle button on "Unlisted". Bonus: put label opacity to 0.5
We probably have to complete the bollow informations like this:

> Public videos are listed on videos page and in browser extension. ([75 pts required](https://captainfact.io/help/privileges))
> 
> Unlisted videos will not be listed on the "videos" page, nor in the browser extension. Use them to work on a content that you don't want to bring forward on the platform. ([15 pts required](https://captainfact.io/help/privileges))

But if you have a better idea, just do it :)

**Comment by steelstyle** [comment]
@Betree I am considering giving another stab at it.

However before investing more time I want to know are we fine with using the same action for limitation ressource ?

**Comment by Miragide** [comment]
> However before investing more time I want to know are we fine with using the same action for limitation ressource ?

I don't know, maybe @Betree can give you an answer?
