### ISSUE TITLE
Users can't connect / site pages doesn't work anymore

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#153]
Users can't connect anymore here https://captainfact.io/login
+ site pages doesn't work anymore

![image](https://user-images.githubusercontent.com/15331478/99151352-ded12680-269a-11eb-8caa-dd4ce6ede929.png)

Console information:
`Access to fetch at 'https://api.captainfact.io/auth/facebook/callback' from origin 'https://captainfact.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Trafic information:
+3000 visitors this day

**Comment by Miragide** [comment]
@Betree SOS :)

**Comment by Miragide** [comment]
I think this bug appear after a facebook id suppression on forestadmin.

**Comment by Betree** [comment]
Resolved by doubling API's capacity (got a out of memory)
