### ISSUE TITLE
Automate saving webpages given as source via web.archive.org

### ISSUE THREAD

**Issue by jibe-b** [CaptainFact/captain-fact#156]
The Wayback Machine keeps successive versions of a webpage.

A webpage might be modified or removed after it is given as a source.

A bot could pass a request to the API to ask for a saving. `curl -X POST https://web.archive.org/save/<URL>` is enough.

A link to the cached webpage could be displayed alongside the source.

**Comment by Betree** [comment]
This one is pretty important. We already have an issue for it though: https://github.com/CaptainFact/captain-fact/issues/51
