### ISSUE TITLE
[feature] freely enter timecode

### ISSUE THREAD

**Issue by jibe-b** [CaptainFact/captain-fact#158]
Right now the timecode is synchronized with the embedded video. And it can be changed by sliding using the left and right arrows.

But this is long and tedious when the video is 12 hours long^^

Enabling to edit the timecode directly (for example with a :pen: button) would enable to enter the timecode freely, for example for the ones who takes note on a paper (^^) or follow the video elsewhere than in the embedded video or when you don't want to stop the live.

**Comment by Betree** [comment]
That'd be great indeed!

Right now the main workaround is to "Unlock" the statement, to move the time cursor on the video then to re-lock it. But that's definitely more tedious.
