### ISSUE TITLE
Défilement automatique via les notifications

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#161]
Je fais part de ce problème présenté sur le forum : 
https://forum.captainfact.io/t/defilement-automatique-via-les-notifications/594/1

drakone 
> Lorsque je clique sur une notif ça ne m’amène pas à la citation concernée. J’ai testé avec les dernières version de Firefox et Chromium (Linux).

Nevjoia
> J’ai le même bug (sur Chrome), mais comme j’ai trouvé un moyen de le contourner, je ne l’ai jamais signalé (honte à moi). En fait, il semblerait que la redirection ne fonctionne pas si on se trouve sur la page même où se trouve le commentaire notifié. Donc je vais sur la page d’accueil, puis je clique sur la notification, et là ça fonctionne. En tout cas chez moi. @drakone tu peux essayer pour voir s’il se passe la même chose chez toi ? Est-ce que d’autres ont le même problème ?

Kawasashi
> J’ai la même chose sur Firefox (windows). Il suffit soit d’aller sur une autre page, soit d’actualiser la page.

**Comment by Betree** [comment]
Probably related to https://github.com/CaptainFact/captain-fact/issues/112

**Comment by Betree** [comment]
From Damien:
> Dans le système de notification, si on clique sur une de nos notifications en n'étant pas sur la page concernée, CaptainFact nous ouvre la page de la vidéo et nous envoie directement au bon "statement"
En revanche, quand on est déjà sur la page, rien ne se passe, alors que la notification devrait nous envoyer également au statement concerné.
