### ISSUE TITLE
Bug lors du clic sur le bouton des notifications

### ISSUE THREAD

**Issue by Nevjoia** [CaptainFact/captain-fact#163]
Le site rencontre une erreur lors du clic sur le bouton des notifications ![image](https://user-images.githubusercontent.com/75577377/101285134-df656480-37e3-11eb-8538-c8b7788466ec.png)

Message d'erreur affiché :
![image](https://user-images.githubusercontent.com/75577377/101285151-f2783480-37e3-11eb-883a-9b4d719b86a2.png)

Le bug ne semble survenir que sur mon compte (Nevjoia). Il est apparu pour la première fois le 01/12/2020.
Le bug est identique sur Chrome et sur Edge. 
OS utilisé : Windows 10

**Comment by Betree** [comment]
Trouvé la source du bug, tu as une notification de quelqu'un qui a répondu à un de tes commentaires puis a supprimé son compte, du coup on arrive pas à afficher la notification correctement. Je publie un fix.
