### ISSUE TITLE
Bouton en savoir plus à coté de la réputation

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#165]
![image](https://user-images.githubusercontent.com/15331478/101535911-99ea9800-3999-11eb-9eb1-87b318dcf52f.png)
Mettre un (?) menant sur la page :  https://captainfact.io/help/reputation
Afin de répondre aux questions fréquentes.

**Comment by Betree** [comment]
Resolved by https://github.com/CaptainFact/captain-fact-frontend/pull/736
