### ISSUE TITLE
Gros problème d'ergonomie sur mobile avec la liste des intervenants

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#171]
Il faudrait mettre une scroll bar à la liste d’intervenants sur mobile, sinon les vérifications sont trop loin dans la page et les personnes ne comprennent pas.

![image](https://user-images.githubusercontent.com/15331478/101563655-f1a0f780-39c9-11eb-9c2c-3ff1ac481f4e.png)

Exemple : https://captainfact.io/videos/4Y7d

**Comment by Betree** [comment]
En mettant une hauteur maximale de 25% de la taille de l'écran sur mobile :

![Peek 2020-12-09 20-49](https://user-images.githubusercontent.com/1556356/101679773-10ea6400-3a60-11eb-89f2-489d57733f4f.gif)
