### ISSUE TITLE
Problème d'ergonomie mobile sur les profils utilisateur

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#172]
Exemple : 
https://captainfact.io/u/laydgeur/activity
![image](https://user-images.githubusercontent.com/15331478/101994040-82741d80-3cbf-11eb-995e-8684716a59ea.png)
Google n'aime pas ça.

**Comment by vguen** [comment]
Tested on my desktop and mobile, this issue only affect my Chrome browser (may affect other Chrome based browser).
