### ISSUE TITLE
Ajouter Mastodon aux réseaux sociaux du site

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#174]
**Icone**
https://styled-icons.js.org/?s=mastodon
@styled-icons/fa-brands/Mastodon

**Lien**
https://mamot.fr/@CaptainFact

**Emplacement**
- Menu
![image](https://user-images.githubusercontent.com/15331478/102264975-ada47a00-3f16-11eb-8999-9273eac45a87.png)

- Page d'accueil
![image](https://user-images.githubusercontent.com/15331478/102265046-c745c180-3f16-11eb-92ce-1aa537d6a40b.png)

**Comment by wdestin** [comment]
Salut, est-ce que je peux m'occuper de ce ticket ? 🙂

**Comment by Miragide** [comment]
Salut @wdestin 
Oui, merci bien 👍 
N'hésite pas à nous rejoindre sur discord pour échanger : https://forum.captainfact.io/t/agenda-de-captainfact/464

**Comment by Betree** [comment]
Implemented by @wdestin in https://github.com/CaptainFact/captain-fact-frontend/pull/729

**Comment by Miragide** [comment]
Merci @wdestin
