### ISSUE TITLE
"Join fact checking forum" link leads to the discord instead of the discourse

### ISSUE THREAD

**Issue by wdestin** [CaptainFact/captain-fact#178]
<img width="958" alt="Screenshot 2020-12-27 at 20 11 31" src="https://user-images.githubusercontent.com/16321487/103178139-72903800-4880-11eb-9747-d14ac0322435.png">

**Comment by Miragide** [comment]
@wdestin bien vu ! Saurais tu remplacer ce lien par « https://forum.captainfact.io/ » ?
Merci
