### ISSUE TITLE
L'extension navigateur ne s'affiche pas sur certaine vidéo YouTube

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#180]
Sur tous les navigateurs.
L'extension CaptainFact ne s'affiche pas sur certaine vidéo.
La vidéo doit être réouverte pour que l'extension s'affiche.
Actualiser la page ne fonctionne pas forcément pour réafficher l'extension.
Ça semble aléatoire.

**Comment by Betree** [comment]
Le reload est un problème connu: https://github.com/CaptainFact/captain-fact/issues/132

Pour le reste on ne pourra pas débugger sans les URLs des vidéos en question mais jusqu'à aujourd'hui toutes les fois où ça a été rapporté le problème venait du fait que l'extension ne s'affiche que lorsqu'il y a au moins 1 commentaire sourcé avec un score de 0 ou plus: https://github.com/CaptainFact/captain-fact-overlay-injector/blob/staging/src/components/Statement/reducer.js#L43.
