### ISSUE TITLE
Gamification: Afficher un objectif journalier de gain de réputation

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#181]
Sujet forum correspondant : https://forum.captainfact.io/t/limite-de-gain-de-reputation-journaliere/687/5
Aujourd'hui, par sécurité un utilisateur ne peut pas gagner plus de 25 pts de réputation par jour.
Cette limite a le défaut d'être invisible.
Il est proposé de rendre cette limite motivante en affichant un objectif journalier sous la forme d'une jauge /25 : 
![image](https://user-images.githubusercontent.com/15331478/104351404-a072af00-5505-11eb-8c54-4b015cf96b8f.png)

L'objectif est de motiver la participation de ceux qui apprécient la gamification.

**Commentaire de** @Betree : 
> plutôt simple à faire en théorie. today_reputation_gain n’est pas encore exposé par l’API mais c’est un simple champ de User. Ça sera compliqué d’afficher la « dernière valeur » au moment exact, mais à ~30 secondes prêt on pourra afficher ça.

**Visuel**
Couleur du texte : #858585 
Couleur de fond de la jauge : #C4C4C4
Hauteur de la jauge : 7 px
Taille du cercle : 19 px
Taille de l'étoile : 12 px
Icone : fa icon-star

**Texte**
Catégorie de menu à ajouter
Texte FR : Votre profil
Texte EN : Your profile

Texte FR : Gain journalier /25
Texte EN : Daily gain

**Bonus**
L'objectif serait à terme d'atteindre ce résultat : 
![image](https://user-images.githubusercontent.com/15331478/104352119-8be2e680-5506-11eb-862d-d1b226f34be3.png)

**Comment by Betree** [comment]
@wdestin did an amazing job at implementing that in https://github.com/CaptainFact/captain-fact-frontend/pull/747 + https://github.com/CaptainFact/captain-fact-api/pull/295.

As a followup to this issue, I think it could be nice to have a little explainer on what this gauge is for new users (quite like the question mark we added at the left the the reputation.

I'll merge & deploy this, and we'll see if that's needed!
