### ISSUE TITLE
Add "localisation" to "About" field

### ISSUE THREAD

**Issue by comradekingu** [CaptainFact/captain-fact#183]
This repo says "Documentation, wiki and community discussions", but nothing about translation/localisation.

**Comment by Miragide** [comment]
Hello @comradekingu 
Translations are in this field:
https://github.com/CaptainFact/captain-fact-frontend/tree/staging/app/i18n
No?

**Comment by comradekingu** [comment]
So it shouldn't be in
![bilde](https://user-images.githubusercontent.com/13802408/108149560-6d5aa700-70d3-11eb-9dd8-5fc1a40b1c28.png)
?

**Comment by Betree** [comment]
Localization is handled primarily in the frontend, so I don't think we should update this specific description. We can however put a link in the README if you think that would be helpful.

**Comment by Betree** [comment]
Closing as they're no clear actionable for me. Feel free to re-open with more specs.
