### ISSUE TITLE
Cannot start the GraphQL API

### ISSUE THREAD

**Issue by wdestin** [CaptainFact/captain-fact#185]
**Describe the bug**

Cannot start the GraphQL API.

**To Reproduce**

*Steps to reproduce the behavior*

1. `git clone https://github.com/CaptainFact/captain-fact-overlay-injector.git`
2. `npm install`
3. `./dev/start_graphql_api.sh`

**Output**

```
Starting containers
Creating dev_database_1 ... done
Creating dev_graphql-api_1 ... done
Waiting for API to be ready...
Running migrations
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/opt/app/bin/captain_fact_graphql\": stat /opt/app/bin/captain_fact_graphql: no such file or directory": unknown
Starting Elixir console. Enjoy !
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/opt/app/bin/captain_fact_graphql\": stat /opt/app/bin/captain_fact_graphql: no such file or directory": unknown
```

**System:**

 - OS: Mac OSx

**Comment by Betree** [comment]
Thanks for reporting this issue @wdestin. Instructions in this project were outdated, I'm updating them in https://github.com/CaptainFact/captain-fact-overlay-injector/pull/240 to match what we have in the frontend.

I personally never use the Docker image in development, so I'm not always able to spot regressions. This installation makes it easier to quickly contribute, but I recommend running [the API](https://github.com/CaptainFact/captain-fact-api) locally for a better dev experience.

**Comment by wdestin** [comment]
Got it!
