### ISSUE TITLE
Ergo : Séparer le bouton "ajouter une citation" des autres actions

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#186]
Citation de MadA sur le forum : https://forum.captainfact.io/t/separer-bouton-ajouter-une-citation-et-autres-actions/867

> Actuellement, le bouton « + » permet à la fois d’ajouter des citations et ouvrir le panel d’options vidéos (autoscroll, notification sonore, modif vidéo, etc). Ce comportement pose plusieurs problèmes :
> 
> il est mal compris par l’utilisateur
> il induit une navigation dégradée sur mobile (à cause des labels notamment)
> Dans les conventions classiques et pour faciliter la compréhension des utilisateurs, il faut respecter la logique : 1 bouton = 1 action
> De ce fait, la proposition d’amélioration présentée la semaine passée est la suivante, séparer les options de l’ajout de citation par la création d’un bouton adapté
> 
> Lien discussion forum : https://forum.captainfact.io/t/ce-que-les-utilisateurs-pensent-de-captain-fact-resultats-recherche-utilisateurs/853/6
> 
> Visuel proto page 7 : https://www.figma.com/proto/CmoFA75xAbFu1CH6ZYxY37/CF_project1?node-id=1%3A57&scaling=scale-down-width 1
> 
> Lien vers spec (anglais) : https://www.notion.so/Project-1-drive-retention-69f7a9ea6a854b4dba6638fd5392cd41?p=81ce9cc6b42941aebc8c850b72302343

![image](https://user-images.githubusercontent.com/15331478/112670604-6a38a080-8e61-11eb-9a54-8dff1ce2c43b.png)

**Alternative (ou en complément de la solution ci dessus) :** 

![image](https://user-images.githubusercontent.com/15331478/113770632-a0f49d80-9722-11eb-91ca-df3240d4203e.png)

Au choix du développeur.

**Comment by adamferal** [comment]
A toi développeur qui me lira, d'un point de vue produit l'option alternative est la meilleure. Dans celle-ci tu auras à choisir le design des boutons : soit garder le design actuel (photo Florence), soit utiliser le deisgn plus épuré de "notification".
 Si tu as des questions sur les dimensions, couleurs, comportements, etc, n'hésite pas 
 
 Tu trouveras les différents requirements ici, de la 1ère option et l'alternative : https://www.notion.so/Project-1-drive-retention-69f7a9ea6a854b4dba6638fd5392cd41?p=81ce9cc6b42941aebc8c850b72302343

Bon courage !

![image](https://user-images.githubusercontent.com/38890362/113854372-169e4f00-979f-11eb-8209-77d1d34628b1.png)
