### ISSUE TITLE
Modification importante de la page d'accueil de CaptainFact.io 

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#206]
## Contexte :
Suite aux délibérations avec la communauté, il est proposé de mettre à jour la page d'accueil de CaptainFact.io ainsi :
https://www.figma.com/proto/KIAqTw6pTvocnDKpuxL2gK/CF-%C3%A9dition?node-id=0%3A3&scaling=min-zoom&page-id=0%3A1

Il s'agit essentiellement de retirer des contenus de la page d'accueil, de la réagencer un peu et de la différencier du nouveau site dédié à la communauté francophone : https://fr.captainfact.io - Ce nouveau site WordPress vise à alléger la page d'accueil de la plateforme ; et à améliorer la communication des activités francophones de CaptainFact, en facilitant la publication des activités relatives au fact-checking collaboratif FR (vitrine, newsletters et notifications navigateurs).

Merci au développeur qui voudra bien se charger d'améliorer la page d'accueil - ne pas hésiter à poser des questions ou à faire des suggestions d'amélioration.

-----------

## Spécifications :

**Visuel :** https://www.figma.com/proto/KIAqTw6pTvocnDKpuxL2gK/CF-%C3%A9dition?node-id=0%3A3&scaling=min-zoom&page-id=0%3A1

Vidéo FR : https://www.youtube.com/watch?v=Hox_CHmC-so
Vidéo autres langues : https://www.youtube.com/watch?v=cZn72yBtIFw (pour remplacer la vidéo FR)

### **IFRAME (FR seulement) « S’abonner au Journal du fact-checking collaboratif » etc.**
Facultatif : mettre cette iframe dans un bloc fermable comme en introduction des pages vidéos https://captainfact.io/videos/Jx6n
Précisions : L'iframe permet de bénéficier facilement du système de newsletter et de notification navigateur du nouveau site WordPress https://fr.captainfact.io/

```
<h2>S’abonner au Journal du fact-checking collaboratif</h2>
<iframe
    width="100%"
    height="600"
    src="https://fr.captainfact.io/iframe-accueil">
</iframe>
```
### **TEXTES FR À METTRE À JOUR**

`Une plateforme web opensource, participative, citoyenne, transparente, ouverte aux différents points de vue et respectueuse de la vie privée.`

`Soyez directement alerté sur YouTube lorsque vous consultez une information fausse ou contestée par la communauté CaptainFact.`
`Découvrir l’extension`

`Rejoignez la communauté, contribuez aux vérifications collaboratives et prenez part à l'un des plus grand combat de notre époque.`
`Rejoindre la communauté`

`Les dernières vidéos en cours de fact-checking collaboratif par les membres`

### **NOUVEAUX TEXTES FR (dans le html ?)**

_Note : les liens suivants sont externes (no-follow + ouverture dans nouvel onglet)_

> Pour en savoir plus sur la communauté francophone de CaptainFact :
> [Partenariats](https://fr.captainfact.io/#partenariat) – [Actions](https://fr.captainfact.io/#actions) – [Journal](https://fr.captainfact.io/presentation-du-journal-du-fact-checking-collaboratif) – [Forum](https://fr.captainfact.io/forum-captainfact) – [Donateurs](https://fr.captainfact.io/#participer) – [Discord](https://discord.gg/Z22Vhda) – [Équipe](https://fr.captainfact.io/equipe)
> Ouvrir le site FR

### **TEXTES EN (et autres langues)** 
Pas de changements

**Comment by Clm-Roig** [comment]
Je peux m'en occuper. J'ai forké le repo et bien avancé là-dessus.

Ce serait ma première issue sur Captain Fact et même ma première contribution à du code open source : je suis preneur de tout commentaire au moment de PR 🙂

**Comment by Miragide** [comment]
Merci beaucoup @Clm-Roig !
Peux tu faire un pull request ici ?
https://github.com/CaptainFact/captain-fact-frontend/pulls

**Comment by Miragide** [comment]
https://github.com/CaptainFact/captain-fact-frontend/pull/868
