### ISSUE TITLE
Augmenter la limite max de caractère des citations de 255 à 280

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#214]
Durant un RDV des utilisateurs de CaptainFact, nous avons remonté une observation : il nous manque souvent la place pour 2 - 3 mots dans l'éditeur de citation, sur la page de vérification des vidéos. Il est donc proposé d'augmenter la limite max de caractère des citations de 255 à 280.

**Comment by Clm-Roig** [comment]
Je m'en suis occupé, je PR dans un instant sur les deux repos 🙂

**Comment by Miragide** [comment]
C'est mergé @Clm-Roig merci beaucoup et désolé pour le retard
