### ISSUE TITLE
Problème SEO des pages history et users

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#217]
**En faisant le bilan statistique et moral 2022 de CaptainFact, j'ai détecté des manques d'optimisation pour les moteurs de recherche.
L'aide d'un développeur (même débutant) est nécessaire pour appliquer des petites corrections.**

## Objectif : désindexer les pages utilisateurs et history
Les pages /history et /u/pseudo sont considérées comme des contenus de faible qualité et les liens vers ces pages font perdre du temps aux robots d'indexation.
Il faut donc : 
- [ ] ajouter dans le head des pages /u/ la balise `<meta name="robots" content="noindex">`
- [x] supprimer les liens vers les pages /u/ depuis les pages vidéos (sur les pseudos des contributeurs) OU ALORS ajouter `rel="nofollow"` dans ces liens
- [x] ajouter dans le head des pages /history la balise `<meta name="robots" content="noindex">`
- [x] ajouter `rel="nofollow"` dans les liens vers les pages /history depuis les pages vidéos

**Comment by Betree** [comment]
Je rejoins le fait que les pages Users et History ne devraient pas être indexées
