### ISSUE TITLE
Modifier la page profil utilisateur

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#218]
Aujourd'hui, cliquer sur le pseudo d'un utilisateur mène sur son profil avec les médailles.
Les médailles ne sont pas les infos les plus pertinentes au sujet de l'utilisateur.
Il est proposé d'inverser "profil" (médailles) par "activité", afin que la page du profil utilisateur commence par ses activités.

**Comment by Miragide** [comment]
Merci @francoispeyret de t'être proposé, n'hésite pas si tu as des questions :)

**Comment by francoispeyret** [comment]
Salut @Miragide,

J'ai un problème avec mon environnement local, la page actualité des utilisateurs n'est pas visible.
![image](https://user-images.githubusercontent.com/15829643/210424365-23487369-d5db-4e7d-ad69-f105c86be5a5.png)
```[GraphQL error]: Message: Cannot query field "authorReputationChange" on type "UserAction"., Location: [object Object], Path: undefined index.js:163:40
[GraphQL error]: Message: Cannot query field "targetReputationChange" on type "UserAction". Did you mean "targetUser"?, Location: [object Object], Path: undefined index.js:163:40
[GraphQL error]: Message: Cannot query field "userId" on type "UserAction". Did you mean "statementId", "speakerId", or "user"?, Location: [object Object], Path: undefined index.js:163:40
[GraphQL error]: Message: Cannot query field "targetUserId" on type "UserAction". Did you mean "targetUser"?, Location: [object Object], Path: undefined index.js:163:40
[GraphQL error]: Message: Unknown argument "direction" on field "actions" of type "User"., Location: [object Object], Path: undefined index.js:163:40
[GraphQL error]: Message: Unknown type "ActivityLogDirection"., Location: [object Object], Path: undefined
```

Je pense que cela vient de la base de donnée locale, à tester sur un environnement ou la page activité était bien fonctionnel.

La PR ci-dessous est en attente de relecture et validation.
https://github.com/CaptainFact/captain-fact-frontend/pull/976

**Comment by Betree** [comment]
Salut @francoispeyret! Probablement le dump API qui n'est pas à jour sur le frontend, il faudrait que je regarde ça. Si jamais, la solution la plus stable reste de cloner https://github.com/CaptainFact/captain-fact-api et de lancer l'API en local.

Merci pour ton fix, il est parfait. J'ai intégré les changements dans la mise à jour de `react-router` qui impliquait de toucher aux mêmes parties du code : https://github.com/CaptainFact/captain-fact-frontend/pull/980.

**Comment by Miragide** [comment]
@francoispeyret @Betree merci beaucoup pour cette amélioration !
Par contre du coup il faut de nouveau ajouter la balise `<meta name="robots" content="noindex">` pour la page /u/ 
J'ai ouvert une issue à ce sujet ici : 
https://github.com/CaptainFact/captain-fact/issues/219

**Comment by Betree** [comment]
Resolved by @francoispeyret
