### ISSUE TITLE
SEO: désindexer toutes les pages profil utilisateur (étape 2)

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#219]
La google search console détecte toujours des problèmes pour les pages utilisateurs.

La résolution de cette issue 
https://github.com/CaptainFact/captain-fact/issues/218
a annulé la résolution d'une partie de cette issue
https://github.com/CaptainFact/captain-fact/issues/217

Les pages /u/pseudo sont considérées comme des contenus de faible qualité et les liens vers ces pages font perdre du temps aux robots d'indexation.
Tout comme dans les pages /u/.../profile il faut donc :
- [ ] ajouter (de nouveau) dans le head des pages /u/ la balise `<meta name="robots" content="noindex">`
- [ ] ajouter dans le head des pages /u/.../videos la balise `<meta name="robots" content="noindex">`

**Comment by Betree** [comment]
La balise no-robots est déjà là sur les pages utilisateurs, example: https://captainfact.io/u/serafean. Elle persiste peut-importe l'onglet choisit.

![image](https://user-images.githubusercontent.com/1556356/212556225-34ae0ae7-eb53-4abc-bad3-e90e5272e3fb.png)

**Comment by Miragide** [comment]
Pourtant ce n'est pas ce que voit le google bot si on inspecte la page https://captainfact.io/u/serafean depuis la Google Search Console contrairement à la page /profile ; la version pour les robots est-elle différente de celle pour les humains @Betree ?

**Comment by Miragide** [comment]
@Betree j'ai compris, c'est à cause du cache google, il n'a pas encore pris en compte le noindex, désolée pour le dérangement du coup.
