### ISSUE TITLE
Problème SEO page speaker /s/ relatif à la pagination

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#220]
![image](https://user-images.githubusercontent.com/15331478/212221738-bf8c94d8-e94a-460f-accc-207f9a1a896b.png)

La google search console détecte 7,5 k erreurs de type "Page en double sans URL canonique sélectionnée par l'utilisateur" notamment sur les pages speaker /s/... parce qu'il existe un lien "mort" vers la page 2 alors qu'il n'existe pas de page 2.

Exemple : 
Sur la page https://captainfact.io/s/Philippe-Pascot
il n'y a pas de page 2
pourtant
le code source contient des liens que les robots google ne comprennent pas comme `href="/s/Philippe-Pascot?page=2"`

`<nav class="pagination is-centered videos-pagination is-rounded" role="navigation" aria-label="pagination"><a class="pagination-previous" disabled="" href="/s/Philippe-Pascot">Page précédente</a><a class="pagination-next" disabled="" href="/s/Philippe-Pascot?page=2">Page suivante</a><ul class="pagination-list"><li><a class="pagination-link is-current" aria-label="Go to page 1" href="/s/Philippe-Pascot">1</a></li></ul></nav>`

Je suppose qu'il suffit de supprimer l'affichage de la pagination lorsqu'il n'y a pas de pagination...

![image](https://user-images.githubusercontent.com/15331478/212222393-6bd9ff9f-3795-4be1-9748-4966465ef0a8.png)

Pour ce qui est des erreurs du type /videos/J...?statement=... : elles sont probablement générées par les pages profils et ce sera résolut avec l'issue https://github.com/CaptainFact/captain-fact/issues/219 "désindexer toutes les pages profil utilisateur".

**Comment by Betree** [comment]
Il faut:
- Définir une URL canonique sur la page speaker (`<link rel="canonical" ... />`) sans le paramètre `page` pour la page 1
- Enlever le `href` de "Page suivante" quand on est sur la dernière page
