### ISSUE TITLE
Extension: Injection does not always work

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#228]
Reported by Yama

:play_or_pause_button: https://www.useloom.com/share/fc6159d2b56041778fa2970d5bbe0047
:play_or_pause_button: https://www.useloom.com/share/7caf466ef0ea4bd092ce2b1dee1c0d9f

**Comment by ghost** [comment]
Here is the behavior that I personally observe on Brave (Chromium). People could try to replicate it to see if it is reliable:
1 - In a new tab, when you enter the Youtube platform through a link that is not a verified video, then go to a verified video, the injection does not work. (ex: https://www.youtube.com/)
2 - In a new tab, when entering Youtube via a verified video link, the injection works. (ex: https://www.youtube.com/watch?v=-8j8xgkZxuE)
3 - Once launched on the tab, the injection works on every video, you can navigate freely on Youtube.
4 - On firefox, page reloading (F5) allows injection (not on Brave)

**Comment by ghost** [comment]
This issue should probably be merged with this one: https://github.com/CaptainFact/captain-fact/issues/180
(opened after a weekly meeting on discord) The problem is the same.
