### ISSUE TITLE
extension page: remove DisMoi

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#232]
"DisMoi" is no longer active.
We should revome it here: 
https://captainfact.io/extension

https://github.com/CaptainFact/captain-fact-frontend/blob/staging/app/components/Pages/BrowserExtensionsPage.jsx
https://github.com/CaptainFact/captain-fact-frontend/blob/staging/app/i18n/fr/extension.json

**Comment by Betree** [comment]
Done & deployed
