### ISSUE TITLE
When all sources goes toward the same side (confirm / refute) show an incitation to participate

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#24]
- [ ] Only show when there is already a confirm or refute column
- [ ] Message must be translated in French and English using `react-i18next`
- [ ] Expend comment form when users click on `Add yours`

# Messages

English strings:
> No source confirming this statement yet. Add yours.
> No source refuting this statement yet. Add yours.

French strings:
> Aucune source ne confirme cette afirmation. Ajouter la vôtre.
> Aucune source ne réfute cette afirmation. Ajouter la vôtre.

# Preview

![Preview](https://trello-attachments.s3.amazonaws.com/58aa18b1e5665006423d2ee0/5b71dea93db27937a378cd7c/9a39f898381c28029ea2e3abb2416e90/S%C3%A9lection_667.png)

**Comment by Betree** [comment]
:money_with_wings: A `20€` bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with `20€` when the Pull Request is reviewed, accepted and merged. [More info](https://github.com/CaptainFact/captain-fact/issues/54).

**Comment by Betree** [comment]
:trophy: This issue has been completed by @vguen 

To claim the **20€** bounty, please submit an invoice to https://opencollective.com/captainfact_io/expenses/new

**Comment by Miragide** [comment]
Hi @vguen can you confirm that this expenses are from you?
https://opencollective.com/captainfact_io/expenses/32640
So that we can proceed.
Thank you :)

**Comment by vguen** [comment]
@Miragide I confirm it's me 🙂
