### ISSUE TITLE
Upload WordPress site backup to restore it on new provider

### ISSUE THREAD

**Issue by fbouffetier** [CaptainFact/captain-fact#241]
## Upload WordPress site backup to restore it  

@Miragide Can you please forward the WordPress site backup so we can restore it..
Please upload it on our Drive in a save folder, or any other secure way. Thanks.

**Comment by fbouffetier** [comment]
@Miragide please update, thanks.

**Comment by Betree** [comment]
The backup is nowhere to be found, we won't be able to restore it.
