### ISSUE TITLE
Setup HMR on frontend

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#47]
As we start using styled-components more and more, having the entire app reloading on each save is slowing us down. We want to add hot module reloading on Webpack to solve this.

Issue will be considered resolved when a change on a component will only reload the given component, not the entire page.

**Comment by Betree** [comment]
:money_with_wings: A `20€` bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with `20€` when the Pull Request is reviewed, accepted and merged. [More info](https://github.com/CaptainFact/captain-fact/issues/54).

**Comment by Betree** [comment]
:trophy: This issue has been completed by @wdestin 

To claim the 20€ bounty, you can submit an invoice to https://opencollective.com/captainfact_io/expenses/new (please mention the issue number in the title).

**Comment by fbouffetier** [comment]
@wdestin Can you please confirm what user id you've used to get the bounty on OpenCollective, in order to justify your identity.
Thanks.

**Comment by wdestin** [comment]
@fbouffetier https://opencollective.com/wid-gael-destin

**Comment by fbouffetier** [comment]
Thanks @wdestin , I'm doing the necessary on OC
