### ISSUE TITLE
Try another message for the home page

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#48]
To be more understandable and to get more users, we should try to change this:

> Let's check the Internet
> Internet est rempli de données riches et diverses. L'information voyage vite et nous n'avons pas le temps de vérifier si tout ce que nous entendons et voyons est correct.
> 
> CaptainFact nous permet de débattre et de nous entraider pour vérifier ces données en les sourçant, en votant et en discutant autour de faits.

For:

> Contribuez à développer l'esprit critique
> et à vérifier les informations
> 
> Pour vous qui voulez des faits : CaptainFact est un outil open-source collaboratif de vérification des informations diffusées sur Youtube.
> Inscrivez-vous pour commencer à sourcer et à fact check les informations.
> Installez notre extention pour bénéficier des faits de CaptainFact directement depuis votre lecteur Youtube.

Let's see
Any other ideas?

**Comment by Betree** [comment]
> Contribuez à développer l'esprit critique et à vérifier les informations.
>
> CaptainFact est un outil open-source qui vous permet de signaler des informations qui vous interpellent sur YouTube pour contribuer à les démentir, à les confirmer ou à les approfondir.
>
> Inscrivez-vous pour commencer à sourcer et à fact-check les informations.
>
> Installez notre extension pour bénéficier des faits de CaptainFact directement depuis votre lecteur YouTube.

**Comment by Betree** [comment]
> Contribuez à développer l'esprit critique et à vérifier les informations.
> 
> CaptainFact est un outil collaboratif de vérification des informations diffusées sur YouTube.
>
> Inscrivez-vous pour commencer à démentir, à confirmer ou à approfondir.
>
> Installez notre extension pour bénéficier des données de CaptainFact directement depuis votre lecteur YouTube.

**Comment by Miragide** [comment]
Super 👍
