### ISSUE TITLE
Speaker title length limit is not clearly displayed to the user

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#55]
> Il y a a priori une longueur maximum de 60 caractères pour le titre d’un intervenant, mais cette limitation n’est connue qu’au retour de la tentative d’enregistrement d’un titre trop long. Par ailleurs, rien ne permet de connaître la longueur du titre que l’on a essayé d’enregistrer (J’ai par exemple dû copier/coller mon titre dans un éditeur pour en connaître la longueur).
> 
> Solutions envisageables :
> 
>   - Un décompte de caractères (potentiellement pénible)
>   - Une limitation “front” sur le champ
>   - Un retour du nombre de caractères utilisés dans le message d’erreur (Vous avez tenté d’insérer X caractères).
>

**Comment by Vayel** [comment]
This issue appears to have been fixed already:

![Title must be at least 3 characters](https://user-images.githubusercontent.com/6124369/54625734-1d4eb200-4a70-11e9-8af3-428b47828cbd.png)

![Title must be at most 60 characters](https://user-images.githubusercontent.com/6124369/54625818-4a02c980-4a70-11e9-8585-2bcc655d0b1f.png)

**Comment by Betree** [comment]
@Vayel The issue mentioned by this user was that we are not aware of the limitation when while/before we type. The validation is done on the API and there's now way to know beforehand that the input's going to be rejected).

As an easy enhancement, I'd be in favor of just changing `Title` to `Title (60 characters max)`.

**Comment by Betree** [comment]
Fixed by https://github.com/CaptainFact/captain-fact-frontend/pull/390
