### ISSUE TITLE
Prefill statement speaker when there is one speaker only

### ISSUE THREAD

**Issue by Vayel** [CaptainFact/captain-fact#61]
When we create a statement to be fact-checked, we can (need to) specify the speaker. When there is only one speaker registered for the video, it would be convenient to have this field automatically filled.

**Comment by Betree** [comment]
Yes! This is a simple and useful improvement. Let's add a bounty on this one.

**Comment by Betree** [comment]
:money_with_wings: A $20 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $20 when the Pull Request is reviewed, accepted and merged. [More info](https://github.com/CaptainFact/captain-fact/issues/54).

**Comment by Betree** [comment]
Resolved by https://github.com/CaptainFact/captain-fact-frontend/pull/377

You can claim the bounty by submitting a 20€ expense on https://opencollective.com/captainfact_io/expenses/new. Please mention the issue number (61) on the expense title.

Thanks again!
