### ISSUE TITLE
Add different background sounds if the statement is refuted or confirmed

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#66]
Related to https://github.com/CaptainFact/captain-fact-frontend/pull/273

---

*Suggested by Az*

**Comment by Vayel** [comment]
https://notificationsounds.com/notification-sounds

**Comment by Vayel** [comment]
What does it mean for a statement to be confirmed (or refuted)? Only with "confirm" sourced comments? Is it confirmed if there are both comments (neither "confirm" or "refute") and "confirm" sourced comments?

**Comment by Betree** [comment]
@Vayel That's a highly political question :)

On the extension we do something totally arbitrary: we sum the score of the comments with **positive** score (negative comments are ignored to avoid trolls undermining a position) and say that a majority of refuting comments is a refuted statement while a majority of confirming comments confirm the statement.

Said with code:

```es6
// Sum all the comments of the statement
const globalStatementScore = comments.reduce((score, comment) => {
  if (comment.approve === true) {
    return score + Math.max(comment.score, 0)
  }
  if (comment.approve === false) {
    return score - Math.max(comment.score, 0)
  }
  return score
}, 0)

// Evaluate this score
if (globalScore > 0) {
  return "confirmed"
}
if (globalScore < 0) {
  return "refuted"
}
return "neutral"
```

I wanted to slightly change this to have a higher threshold than 0 (eg. globalScore > 3 or globalScore < -3).

**Comment by Vayel** [comment]
@Betree `comment.approve` is a boolean but a comment can be in three states: `approve`, `refute`, `comment`. How do you represent the last one?

**Comment by Betree** [comment]
Comments have `comment.approve === null`

**Comment by Betree** [comment]
Implemented in https://github.com/CaptainFact/captain-fact-frontend/pull/417
