### ISSUE TITLE
Display what "fact-checker" and "viewer" mean

### ISSUE THREAD

**Issue by Vayel** [CaptainFact/captain-fact#77]
![](https://user-images.githubusercontent.com/6124369/54688641-4e85bb80-4b1e-11e9-9c9f-b52c05a7be58.png)

## User story 

As a user, I clearly know what "fact-checker" and "viewer" mean.

## Best solution for this problem

I can be done simply by adding a `title` attribute to the elements.

I guess "fact-checker" means "person connected to the platform". But I don't whether "viewer" means "non-connected person watching the video on the platform" or "person watching the video on Youtube".

**Edit:** two wordings were defined below:

* `Registered user currently watching this video`
* `Unregistered user currently watching this video on CaptainFact`

The titles for the screenshot above would then be:

* `3 registered users currently watching this video`
* `6 unregistered users currently watching this video on CaptainFact`

**Comment by Betree** [comment]
To be more precise, I'd say:
1. `Registered user currently watching this video`
2. `Unregistered user currently watching this video`

Not sure though if `2.` properly clarifies that it's the number of viewers on CaptainFact, not on YouTube.

Feel free to propose something that suits you better.

And thanks for the issues you open @Vayel, they're really on point!

**Comment by Vayel** [comment]
`    Unregistered user currently watching this video on CaptainFact` is a bit long but makes it crystal-clear. And I don't think the length is a problem because people will read the definition only once, at most twice. 

Is it ok for you @Betree?

**Comment by Betree** [comment]
@Vayel 100% agree with this wording and on the fact that it is not a problem if it's long, especially because it's only displayed on hover. Let's do that.

**Comment by Vayel** [comment]
@Betree I suggest for this issue to be a `good first issue`. I think it is a good opportunity for someone to join the project.

**Comment by Miragide** [comment]
@Vayel [une solution plus radicale ](https://github.com/CaptainFact/captain-fact/issues/137) a été adoptée, j'espère qu'elle te plait également. Merci d'avoir souligné ce problème :)
