### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#85]
# Specs

*TODO*

# Design

See https://www.figma.com/proto/ERpy0f1Ek4CSmLSZRQOFU1tC/CaptainFact?node-id=674%3A9104&scaling=min-zoom

**Comment by samber** [comment]
![](https://media.giphy.com/media/1rlIAa3dAb3os/giphy.gif)

😍

**Comment by CyrilToonkit** [comment]
OMG

**Comment by CyrilToonkit** [comment]
OMG

**Comment by Miragide** [comment]
Proposition de design : 
https://www.figma.com/proto/ERpy0f1Ek4CSmLSZRQOFU1tC/CaptainFact?node-id=674%3A9104&scaling=min-zoom

**Comment by Betree** [comment]
The initial version released in https://github.com/CaptainFact/captain-fact-frontend/pull/780, only available for logged in users for now. We'll enable it for everyone once we'll have a clearer idea of the usage.
