### ISSUE TITLE
Langue arabe et support RTL (right to left)

### ISSUE THREAD

**Issue by HamidTiouti** [CaptainFact/captain-fact#88]
Bonjour,
Serait il possible d’implémenter la langue arabe sur l’interface CaptainFact?
Traduction de l’Interface et ajout du support RTL

**Comment by Betree** [comment]
Merci pour le ticket @HamidTiouti :slightly_smiling_face: 

On a 3 types de contenus à traduire:

- [ ] **Interface**

Tout se passe ici : https://github.com/CaptainFact/captain-fact-frontend/tree/staging/app/i18n

Il faut copier le dossier `captain-fact-frontend/app/i18n/fr` vers `captain-fact-frontend/app/i18n/dz` et traduire les fichiers qui sont à l'intérieur.

- [ ] **Pages d'aide**

Pour les pages d'aides il y a une interface en ligne ici: https://gitlocalize.com/repo/1745/ar-DZ/app/static/assets/help/fr

- [ ] **Mails**

Pour les mails ça se passe [ici](https://github.com/CaptainFact/captain-fact-api/tree/staging/apps/cf/lib/mailer/templates) mais c'est un peu plus compliqué. On peut peut-être voir ça dans un deuxième temps.

---

Pour le RTL je peux regarder ça de mon côté mais si tu veux prendre de l'avance les styles sont [ici (SASS)](https://github.com/CaptainFact/captain-fact-frontend/tree/staging/app/styles). On met la locale dans une `div` parente donc le code suivant devrait marcher:

```sass
div[lang=dz] {
  direction: rtl;
}
```

---

Est-ce que tu es à l'aise avec tous les outils listés ici ?

Ps: On est aussi sur [Discord](https://discord.gg/2Qd7hMz) si jamais tu as besoin de discuter en chat.

**Comment by BoFFire** [comment]
Hi @Betree can we have neutral `ar` instead of regional ar_DZ ? This in case we have to use some MT for translation.
Thank you,
Merci,

**Comment by Betree** [comment]
@BoFFire Sure, I just moved the translation interface to https://gitlocalize.com/repo/1745/ar/app/static/assets/help/fr

**Comment by BoFFire** [comment]
Bonjour @Betree 
Serait-ce possible d'avoir un moyen afin que les *.js puissent être exportés/importés sur/depuis un Weblate ou toute autre plateforme de traduction afin de bosser dessus aisément ? J'ai tenté d'importer les chaînes à traduire mais comme si ça n'accepte pas vraiment d'architecture du fichier.
Merci encore.

**Comment by Betree** [comment]
Une possibilité serait d'avoir du JSON à la place des .js. Je vois que Weblate le supportent (http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/index.html).

D'ailleurs je ne connaissais pas cet outil, ça a l'air top. Une fois la modif faite je les contacterais pour avoir un hebergement (j'ai vu qu'il sont gratuits pour les projets libres).

=> https://github.com/CaptainFact/captain-fact/issues/105

**Comment by BoFFire** [comment]
@Betree merci beaucoup \o/

**Comment by Betree** [comment]
@BoFFire J'ai bougé les traductions sur du JSON et contacté Weblate. Je mettrais à jour ce ticket dès que j'ai une réponse.

**Comment by BoFFire** [comment]
See https://github.com/CaptainFact/captain-fact/issues/105#issuecomment-499587609

**Comment by Betree** [comment]
Résolu par https://github.com/CaptainFact/captain-fact-frontend/pull/476
