### ISSUE TITLE
Admin tools for ambassadors

### ISSUE THREAD

**Issue by fbouffetier** [CaptainFact/captain-fact#90]
## Create a administrator access and module to offer special access

Modify video categories (User or partners), update video link (Some video on youtube can be reuploaded, then the url change), delete vidéo (For moderation reason), edit comment (From all users/partnairs to update mistake on syntax or in case of user ask for an update).

## Best solution for this problem

*Need to be clarify. Need to think every possibilities offer by the administrator module. Next feature will have to be anticipated to integrate necessarely module.*

**Comment by fbouffetier** [comment]
Issue updated with more details.

**Comment by fbouffetier** [comment]
Issue updated with reason of asking admin tools.

**Comment by Miragide** [comment]
Ceci est désormais possible facilement en demandant à l'équipe technique depuis le forum ou le discord.
