### ISSUE TITLE
Show unread moderations entries count on sidebar

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact#95]
![image](https://user-images.githubusercontent.com/1556356/55352255-52b7be80-54b8-11e9-94e6-3f2a8e8cd528.png)

**Comment by steelstyle** [comment]
How should this look like ? Just a plain number ?

**Comment by Miragide** [comment]
> How should this look like ? Just a plain number ?

@steelstyle i suggest this:
- #E0454E
- https://bulma.io/documentation/elements/tag/

**Comment by steelstyle** [comment]
Great, sorry for the late reply.

@Betree as I'm not sure what is the convention to transit  such information in this app.
Can you tell me if a vanilla rpc would be okay, of if there is another way you wrap this kind of data ?
Would like to have an idea to know how much of an effort this is.

**Comment by Betree** [comment]
The moderation feature is unfortunately still plugged on the legacy REST endpoints.

The new way to communicate between frontend & API is through GraphQL. You can try it there: https://graphql.staging.captainfact.io/graphiql

Because there's no REST endpoint to get the total number of pending moderation items, I would recommend to implement it directly on GraphQL. Here's a suggestion on how that can be done:
- Add a `count_items_to_review(user)` function in `apps/cf/lib/moderation/moderation.ex` (feel free to find a better name). You can copy paste most of the code from `random!(user)` to implement it.
- On `apps/cf_graphql/lib/schema/types/user.ex`, add a `pending_moderation_items_count` field, with a resolver that calls `CF.Moderation.count_items_to_review(user)`. Eventually pass it through a `middleware(Middleware.RequireAuthentication)`?

On the frontend, you'll then be able to fetch this field with a `useQuery` (see Apollo's documentation)

**Comment by Betree** [comment]
Edit: just saw your [PR](https://github.com/CaptainFact/captain-fact-api/pull/274) @steelstyle, sounds like you found the solution by yourself :wink: I'll review now!

**Comment by Miragide** [comment]
Merci beaucoup @steelstyle @Betree ! Cela va énormément faciliter la vie des modérateurs :)
